/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogRouteImport } from './routes/log'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as FinanceAccountsRouteImport } from './routes/finance/accounts'
import { Route as FinanceBudgetsRouteImport } from './routes/finance/budgets'
import { Route as FinanceCurrenciesRouteImport } from './routes/finance/currencies'
import { Route as FinanceSpendingRouteImport } from './routes/finance/spending'
import { Route as FinanceSubscriptionsRouteImport } from './routes/finance/subscriptions'
import { Route as FinanceTransactionsRouteImport } from './routes/finance/transactions'
import { Route as HabitsIndexRouteImport } from './routes/habits/index'
import { Route as HabitsHabitIdRouteImport } from './routes/habits/$habitId'
import { Route as HabitsHistoryRouteImport } from './routes/habits/history'
import { Route as HabitsTodayRouteImport } from './routes/habits/today'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalCalendarRouteImport } from './routes/journal/calendar'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksListsIndexRouteImport } from './routes/tasks/lists/index'
import { Route as TasksListsListIdRouteImport } from './routes/tasks/lists/$listId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/finance/accounts',
  path: '/finance/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/finance/budgets',
  path: '/finance/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCurrenciesRoute = FinanceCurrenciesRouteImport.update({
  id: '/finance/currencies',
  path: '/finance/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceSpendingRoute = FinanceSpendingRouteImport.update({
  id: '/finance/spending',
  path: '/finance/spending',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceSubscriptionsRoute = FinanceSubscriptionsRouteImport.update({
  id: '/finance/subscriptions',
  path: '/finance/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/finance/transactions',
  path: '/finance/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsHabitIdRoute = HabitsHabitIdRouteImport.update({
  id: '/habits/$habitId',
  path: '/habits/$habitId',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsHistoryRoute = HabitsHistoryRouteImport.update({
  id: '/habits/history',
  path: '/habits/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsTodayRoute = HabitsTodayRouteImport.update({
  id: '/habits/today',
  path: '/habits/today',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalCalendarRoute = JournalCalendarRouteImport.update({
  id: '/journal/calendar',
  path: '/journal/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksListsIndexRoute = TasksListsIndexRouteImport.update({
  id: '/tasks/lists/',
  path: '/tasks/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksListsListIdRoute = TasksListsListIdRouteImport.update({
  id: '/tasks/lists/$listId',
  path: '/tasks/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/currencies': typeof FinanceCurrenciesRoute
  '/finance/spending': typeof FinanceSpendingRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/history': typeof HabitsHistoryRoute
  '/habits/today': typeof HabitsTodayRoute
  '/journal/calendar': typeof JournalCalendarRoute
  '/finance/': typeof FinanceIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/lists/$listId': typeof TasksListsListIdRoute
  '/tasks/lists/': typeof TasksListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/currencies': typeof FinanceCurrenciesRoute
  '/finance/spending': typeof FinanceSpendingRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/history': typeof HabitsHistoryRoute
  '/habits/today': typeof HabitsTodayRoute
  '/journal/calendar': typeof JournalCalendarRoute
  '/finance': typeof FinanceIndexRoute
  '/habits': typeof HabitsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/lists/$listId': typeof TasksListsListIdRoute
  '/tasks/lists': typeof TasksListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/currencies': typeof FinanceCurrenciesRoute
  '/finance/spending': typeof FinanceSpendingRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/history': typeof HabitsHistoryRoute
  '/habits/today': typeof HabitsTodayRoute
  '/journal/calendar': typeof JournalCalendarRoute
  '/finance/': typeof FinanceIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/lists/$listId': typeof TasksListsListIdRoute
  '/tasks/lists/': typeof TasksListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/log'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/currencies'
    | '/finance/spending'
    | '/finance/subscriptions'
    | '/finance/transactions'
    | '/habits/$habitId'
    | '/habits/history'
    | '/habits/today'
    | '/journal/calendar'
    | '/finance/'
    | '/habits/'
    | '/journal/'
    | '/tasks/'
    | '/tasks/lists/$listId'
    | '/tasks/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/log'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/currencies'
    | '/finance/spending'
    | '/finance/subscriptions'
    | '/finance/transactions'
    | '/habits/$habitId'
    | '/habits/history'
    | '/habits/today'
    | '/journal/calendar'
    | '/finance'
    | '/habits'
    | '/journal'
    | '/tasks'
    | '/tasks/lists/$listId'
    | '/tasks/lists'
  id:
    | '__root__'
    | '/'
    | '/log'
    | '/finance/accounts'
    | '/finance/budgets'
    | '/finance/currencies'
    | '/finance/spending'
    | '/finance/subscriptions'
    | '/finance/transactions'
    | '/habits/$habitId'
    | '/habits/history'
    | '/habits/today'
    | '/journal/calendar'
    | '/finance/'
    | '/habits/'
    | '/journal/'
    | '/tasks/'
    | '/tasks/lists/$listId'
    | '/tasks/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogRoute: typeof LogRoute
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceBudgetsRoute: typeof FinanceBudgetsRoute
  FinanceCurrenciesRoute: typeof FinanceCurrenciesRoute
  FinanceSpendingRoute: typeof FinanceSpendingRoute
  FinanceSubscriptionsRoute: typeof FinanceSubscriptionsRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  HabitsHabitIdRoute: typeof HabitsHabitIdRoute
  HabitsHistoryRoute: typeof HabitsHistoryRoute
  HabitsTodayRoute: typeof HabitsTodayRoute
  JournalCalendarRoute: typeof JournalCalendarRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TasksListsListIdRoute: typeof TasksListsListIdRoute
  TasksListsIndexRoute: typeof TasksListsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/finance/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/finance/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/currencies': {
      id: '/finance/currencies'
      path: '/finance/currencies'
      fullPath: '/finance/currencies'
      preLoaderRoute: typeof FinanceCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/spending': {
      id: '/finance/spending'
      path: '/finance/spending'
      fullPath: '/finance/spending'
      preLoaderRoute: typeof FinanceSpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/subscriptions': {
      id: '/finance/subscriptions'
      path: '/finance/subscriptions'
      fullPath: '/finance/subscriptions'
      preLoaderRoute: typeof FinanceSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/': {
      id: '/habits/'
      path: '/habits'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/habits/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/history': {
      id: '/habits/history'
      path: '/habits/history'
      fullPath: '/habits/history'
      preLoaderRoute: typeof HabitsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/today': {
      id: '/habits/today'
      path: '/habits/today'
      fullPath: '/habits/today'
      preLoaderRoute: typeof HabitsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/calendar': {
      id: '/journal/calendar'
      path: '/journal/calendar'
      fullPath: '/journal/calendar'
      preLoaderRoute: typeof JournalCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/lists/': {
      id: '/tasks/lists/'
      path: '/tasks/lists'
      fullPath: '/tasks/lists/'
      preLoaderRoute: typeof TasksListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/lists/$listId': {
      id: '/tasks/lists/$listId'
      path: '/tasks/lists/$listId'
      fullPath: '/tasks/lists/$listId'
      preLoaderRoute: typeof TasksListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogRoute: LogRoute,
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceBudgetsRoute: FinanceBudgetsRoute,
  FinanceCurrenciesRoute: FinanceCurrenciesRoute,
  FinanceSpendingRoute: FinanceSpendingRoute,
  FinanceSubscriptionsRoute: FinanceSubscriptionsRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  HabitsHabitIdRoute: HabitsHabitIdRoute,
  HabitsHistoryRoute: HabitsHistoryRoute,
  HabitsTodayRoute: HabitsTodayRoute,
  JournalCalendarRoute: JournalCalendarRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  HabitsIndexRoute: HabitsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TasksListsListIdRoute: TasksListsListIdRoute,
  TasksListsIndexRoute: TasksListsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
